name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Create Github Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: 🏭 Create Release
      run: |
        gh release create ${{ github.ref }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: ⏫ Upload to Hackage
    #   id: upload_hackage
    #   env:
    #     HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
    #   uses: freckle/stack-upload-action@main
